spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
    prefix: classpath:/static/

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/questionnaire
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 20
        min-idle: 1
        max-active: 20
        max-wait: 60000
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 60000
        min-idle: 0
      shutdown-timeout: 100ms

logging:
  file:
    path: /home/zqq/questionnaire/logs
  config: classpath:logback-spring.xml
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}]--[%-5p]:[%c]--%m%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss}]--[%-5p]:[%c]--%m%n"

server:
  port: 8888

access:
  url: http://127.0.0.1:84
  bgURLf: bg/%d.jpg
  fgURLf: fg/%d.jpg
  tnURLf: thumbnail/%d.png
